### PR TITLE
feature: select env-s in which the scaffold runs.

### PR DESCRIPTION
**Pull request by athikrishnan**
Allow the user to select environments in which the /scaffold url's will be allowed.

requires the following middleware to be added to global HTTP middleware stack.

```
\Amranidev\ScaffoldInterface\Http\Middleware\ScaffoldMiddleware::class,
```

and the environments are selected under 

```
config\scaffold.php
```

### CODE REVIEW

**Comment by amranidev** [comment]
@athikrishnan 
Thanks !! 
Already have a config file.
`env` should be added to `config/amranidev/config.php`

**Comment by athikrishnan** [comment]
```
1) Amranidev\ScaffoldInterface\Tests\BehavioralTest::testPaths
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'C:\Users\athithan\Works\scaffold\scaffold-interface\vendor\orchestra\testbench\src\Traits/../../fixture\app\Test_abraham.php'
+'C:\Users\athithan\Works\scaffold\scaffold-interface\vendor\orchestra\testbench\src\Traits/../../fixture/app/Test_abraham.php'
```

any idea why its happening?

and also, does the config file you mentioned published into laravel config directory?

**Comment by amranidev** [comment]
@athikrishnan yes the config file publishes into laravel config directory config/amranidev/config.php.

**Comment by amranidev** [comment]
@athikrishnan Anyway
I will merge it and fix it
Thanks

**Pull request merged**
